name: Deploy Nginx Force

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout do Codigo'
        uses: actions/checkout@v4

      - name: 'Login na Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy via Azure CLI'
        run: |
          az webapp config container set \
            --name lckwebapp \
            --resource-group lockton-br-rg-devops \
            --docker-custom-image-name nginx:latest
