name: Teste Conexao Azure Nginx

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Permite rodar manualmente no botão "Run workflow"

jobs:
  deploy-teste:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout do Codigo'
        uses: actions/checkout@v4

      - name: 'Deploy para Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          # ATENÇÃO: Verifique se o nome abaixo é EXATAMENTE o que aparece no portal
          app-name: 'lckwebapp' 
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'nginx:latest'
